### ISSUE TITLE
Is this job suitable for license plate style transfer？

### ISSUE THREAD

**Issue by guoguangchao** [open-mmlab/StyleShot#37]
thanks for your great work,I want to transfer standard license plates to real fuzzy license plates,and I hope the character content of the license plate remains unchanged.my content image is a standard license plate,style image is a real fuzzy license,I tried the pre trained model and the results were quite bad：
content image:
![京2GFMQS_blue_False_real_A](https://github.com/user-attachments/assets/c747e166-b402-478b-9b9f-83d680f10bba)
style image:
![hu](https://github.com/user-attachments/assets/d92a09e7-b845-4121-9722-efa3393d3a3e)
result:
![image](https://github.com/user-attachments/assets/e9371939-b510-44b7-9791-21a55ef42f6d)
I would like to ask if this job is suitable for this task?If there are many standard license plates and many fuzzy license plates without corresponding matching pairs, can we achieve the goal through finetune?thaks a lot

**Comment by Jeoyal** [comment]
Hi @guoguangchao , thank you for your interest in our work. We have released [StyleShot lineart](https://huggingface.co/Gaojunyao/StyleShot_lineart) for the fine-grained content control, which you can use for inference.
Additionally, you can adjust the content/style control scale as needed.
Lastly, I am not sure if fine-tuning will achieve better results. For a more stable fuzzy style transfer, i suggest trying some traditional blurring algorithms rather than a generative model.

**Comment by guoguangchao** [comment]
> Hi @guoguangchao , thank you for your interest in our work. We have released [StyleShot lineart](https://huggingface.co/Gaojunyao/StyleShot_lineart) for the fine-grained content control, which you can use for inference. Additionally, you can adjust the content/style control scale as needed. Lastly, I am not sure if fine-tuning will achieve better results. For a more stable fuzzy style transfer, i suggest trying some traditional blurring algorithms rather than a generative model.

tanks for your reply, I will try
